[package]
name = "array90"
version = "0.1.0"
authors = ["Jeudi Prando Araujo <jeudi.araujo@el.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
